### ISSUE TITLE
Stopped functioning today?

### ISSUE THREAD

**Issue by MrNickIE** [klejejs/ha-thermia-heat-pump-integration#101]
Hello,

Thanks for this plugin.  I have been using for years.

Today, it stopped working, but appears to still be logged into our thermia online account.  This is soon after a HA upgrade to latest version.  Any ideas?

I have removed the working integration, that had a device with everything unavailable.  I have reinstalled the HACS addin again, and rebooted and now it is simply not detecting any device at all.

**Comment by MrNickIE** [comment]
Found this in debugs?

2024-11-27 17:36:46.879 DEBUG (MainThread) [custom_components.thermia] Finished fetching thermia data in 0.001 seconds (success: True)
2024-11-27 17:36:51.303 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
    self._protocol.datagram_received(data, addr)

**Comment by ReconOperator** [comment]
There was some maintenance done today by Thermia so this might be the reason? 

![Capture](https://github.com/user-attachments/assets/af6f185f-76e4-49bf-8fcf-0f2f63df1ad9)

**Comment by MrNickIE** [comment]
Oh my, I do pick my days :)

**Comment by ReconOperator** [comment]
But i check my installation in HA and the logs.

2024-11-27 19:11:49.486 ERROR (SyncWorker_15) [ThermiaOnlineAPI.api.ThermiaAPI] Error getting device by id: 1528732
2024-11-27 19:12:00.435 ERROR (SyncWorker_25) [ThermiaOnlineAPI.api.ThermiaAPI] Error getting device by id: 1528732
2024-11-27 19:12:11.456 ERROR (SyncWorker_21) [ThermiaOnlineAPI.api.ThermiaAPI] Error getting device by id: 1528732
2024-11-27 19:12:22.469 ERROR (SyncWorker_47) [ThermiaOnlineAPI.api.ThermiaAPI] Error getting device by id: 1528732

I did a reload of the integration after i saw that and now it is unavailable

I had now issue before Thermia did something on their side

**Comment by ReconOperator** [comment]
Checked my geothermal pump and it seems that data is not updating on online.thermia
