### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by frealv** [klejejs/ha-thermia-heat-pump-integration#16]
I get this(2022.2.2)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 401, in async_get_or_create
    entity_category=_convert_to_entity_category(entity_category),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 103, in _convert_to_entity_category
    return convert_to_entity_category(value, raise_report=raise_report)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 220, in convert_to_entity_category
    return EntityCategory(value)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'sensor' is not a valid EntityCategory

**Comment by klejejs** [comment]
I have released a new version that fixes the problem.
In case you have an issue of HA not starting, please delete `thermia` folder from `config/custom_components` directory and also please edit `config/.storage/core.entity_registry` file and delete all objects that include `"device_class": "sensor"` to make sure that the issue does not appear again.
After doing this and restarting Home Assistant, you should be able to redownload the integration from HACS and everything will be working. No need to re-add heat pumps.
Sorry for the inconvenience :(.

**Comment by frealv** [comment]
Thanks for your effort…Its appreciated!!!

Mvh,
/Fredrik

**Comment by klejejs** [comment]
No problem, althogh @danialclements deserves the credit, he fixed the issue.
