### ISSUE TITLE
Error setting register 

### ISSUE THREAD

**Issue by zama737** [klejejs/ha-thermia-heat-pump-integration#49]
Hi, 

After running successfully this integration for several months, started suddenly face issue with Thermia integration this week. For some reason it does not set values to the pump. Readings seems to be updating ok. 

No success so far, did try to fix it:
1. Reloaded the integration,
2. Did update to the latest custom integration files
3. Removed and reinstalled integration
4. System restart
6. Did install version of latest HA

For example when setting temperature, log is giving error below. Any ideas what could be wrong?

```
This error originated from a custom integration: 

Logger: ThermiaOnlineAPI.api.ThermiaAPI
Source: custom_components/thermia_water_heater/water_heater.py:145
Integration: thermia_water_heater
First occurred: 14:38:18 (2 occurrences)
Last logged: 14:38:23

Error setting register 6010 value. 400
```
![Thermia error](https://user-images.githubusercontent.com/47860917/227525749-1089c8cf-fb27-4e76-bc71-4f27d7508b10.jpg)

Pump used is: 
Thermia Diplomat Duo Optimum

HA version: 
Home Assistant 2023.3.6
Supervisor 2023.03.2
Frontend 20230309.1 - latest

Thermia's app seems to be working just fine. 
Thanks!

**Comment by zama737** [comment]
There seems to be more in logs: 

`2023-03-24 14:34:15.034 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for thermia_water_heater using this method at custom_components/thermia_water_heater/__init__.py, line 51: hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
2023-03-24 14:34:15.038 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing thermia/diagnostics.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.thermia_water_heater.diagnostics'
2023-03-24 14:34:15.040 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing thermia/recorder.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.thermia_water_heater.recorder'
2023-03-24 14:34:15.041 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing thermia/group.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.thermia_water_heater.group'
2023-03-24 14:34:15.041 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing thermia/system_health.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.thermia_water_heater.system_health'
2023-03-24 14:34:15.042 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing thermia/media_source.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.thermia_water_heater.media_source'
2023-03-24 14:34:15.042 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing thermia/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.thermia_water_heater.logbook'
2023-03-24 14:34:21.747 INFO (MainThread) [custom_components.pyscript.global_ctx] Loaded /config/pyscript/test.py
2023-03-24 14:34:21.770 WARNING (MainThread) [homeassistant.components.switch] Platform broadlink not ready yet: None; Retrying in background in 30 seconds
2023-03-24 14:34:21.771 WARNING (MainThread) [homeassistant.components.switch] Platform broadlink not ready yet: None; Retrying in background in 30 seconds
2023-03-24 14:34:32.799 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing thermia/cast.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.thermia_water_heater.cast'`

**Comment by flexi80** [comment]
Have you tried updating the integration in the last 24hr? If not then do so, and some of the functionality will come back.

**Comment by PalmSwe** [comment]
Also have error. Even after update.

Error setting register 1363 value. 400

**Comment by eljobo** [comment]
Even after update I still get an error when trying to set "operation status". I've installed the integration twice and restarted HA.

This error originated from a custom integration.

Logger: ThermiaOnlineAPI.api.ThermiaAPI
Source: custom_components/thermia/water_heater.py:156
Integration: Thermia Heat Pump (documentation, issues)
First occurred: 10:33:40 AM (1 occurrences)
Last logged: 10:33:40 AM

Error setting register 51 value. 400

**Comment by VezQu** [comment]
I have also had this error for a few days now. Unable to set the on/off state for hot water or boost.

ERROR (SyncWorker_0) [ThermiaOnlineAPI.api.ThermiaAPI] Error setting register 1059 value. 400
ERROR (SyncWorker_5) [ThermiaOnlineAPI.api.ThermiaAPI] Error setting register 926 value. 400

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Thermia Heat Pump Integration 2.18
Heat Pump: Thermia Calibra 7

Restarted HA and reinstalled the integration multiple times.

**Comment by d-flower** [comment]
Have you found a way to turn the water function on and off? I still have the same problem with setting a new register value.

**Comment by PalmSwe** [comment]
Also still have the same problem. Can't turn the heater on or off.

**Comment by VezQu** [comment]
I am able to control the heater temperature, but unable to control the switches for hot water or boost.

**Comment by klejejs** [comment]
There were further Thermia API changes. Please check if there are still issues with the latest version and reopen the issue if problems persist.

**Comment by PalmSwe** [comment]
Seems to work as I wish! Now I can turn heater and water on/off without any problem!

Thanks! 😃

**Comment by zama737** [comment]
After updating to latest files it works as expected. Many thanks @klejejs!

**Comment by zama737** [comment]
After latest updates thermia integration stops updating frequently, typically every 2-3 days. Probably something to do with api updates. Reloading integration helps, updates resumes to normal after reload. Anyone else having issues with updates?

**Comment by klejejs** [comment]
@zama737 it seems Thermia has started throwing errors for some requests. I attempted fixing it with the latest release 3.1.1.

**Comment by zama737** [comment]
Thanks @klejejs, did install latest release and will see if it works now. 

After installing latest version, it seems that "desired supply line temp" was lost. It shows entity not available. Did remove and reinstall integration, it did not bring desired supply line temp back. Any ideas?
