### ISSUE TITLE
ValueError for operational_status

### ISSUE THREAD

**Issue by linusmahler** [klejejs/ha-thermia-heat-pump-integration#58]
The `operational_status` does not work, with the below tracelog.

**Using**: https://www.online-genesis.thermia.se/
**Heatpump**: 
Calibra Eco 8
Software version
12.1.5

I don't know if it used to be a numerical value, but it appears it's either one of these now:

![Skärmavbild 2023-09-13 kl  20 22 58](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/4963123/4163a3bb-2ed0-4e22-bcaa-b6bac1de03e2)

I don't know if the shown operational statuses are the exhaustive list, or just a subset associated with my heatpump.

Hopefully it's always a string value now and an easy fix, otherwise I would assume (not knowing how to extract the values) it's the same pattern for all of them, i.e

* STATUS_MANUAL
* STATUS_HOT_WATER
* STATUS_HEATING
* STATUS_ACTIVE_COOLING
* STATUS_ POOL
* STATUS_PASSIVE_COOLING
* STATUS_STANDBY
* STATUS_NO_DEMAND
* STATUS_OFF

Let me know if there is any other information that would be helpful.

```
Logger: homeassistant
Source: components/sensor/__init__.py:593
First occurred: 9:10:32 AM (3478 occurrences)
Last logged: 7:47:47 PM
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 586, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'STATUS_NO_DEMAND'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 589, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'STATUS_NO_DEMAND'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 235, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 473, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 593, in state
    raise ValueError(
ValueError: Sensor sensor.bergvarmen_operational_status has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'STATUS_NO_DEMAND' (<class 'str'>)
```

**Comment by jondavidsson** [comment]
Here's some information from the Thermia online API regarding the:
Operational status
Operational status: STATUS_HEAT
Available operational statuses: ['OPERATION_MODE_OFF', 'STATUS_NO_DEMAND', 'STATUS_STANDBY', 'STATUS_PASSIVE_COOL', 'STATUS_LEGIONELLA', 'STATUS_POOL', 'STATUS_COOL', 'STATUS_HEAT', 'STATUS_HOTWATER', 'STATUS_DEFROST', 'STATUS_MANUAL']
Available operational statuses map: ChainMap({1: 'STATUS_MANUAL'}, {2: 'STATUS_DEFROST'}, {4: 'STATUS_HOTWATER'}, {8: 'STATUS_HEAT'}, {16: 'STATUS_COOL'}, {32: 'STATUS_POOL'}, {64: 'STATUS_LEGIONELLA'}, {128: 'STATUS_PASSIVE_COOL'}, {512: 'STATUS_STANDBY'}, {1024: 'STATUS_NO_DEMAND'}, {2048: 'OPERATION_MODE_OFF'})
Auxiliary heater 3KW: None
Auxiliary heater 6KW: None
Auxiliary heater 9KW: None
Auxiliary heater 12KW: None
Auxiliary heater 15KW: None
Compressor status: None
Brine pump status: None
Radiator pump status: None
Cooling status: None
Hot water status: None
Heating status: None
Integral: None
Pid: None

**Comment by klejejs** [comment]
The sensor always has returned a string value, it seems one of the latest HA releases broke the functionality as it assumed the sensor value was a number. The latest release fixes that.
