### ISSUE TITLE
Integration not working after updating to HA 2023.10.1

### ISSUE THREAD

**Issue by AndreasBroager** [klejejs/ha-thermia-heat-pump-integration#61]
After update of HA to: 2023.10.1 the Thermia integration doesn't work. HA gets no values, and HA cannot control my heat pump.

My Thermia heat pump is: Calibra cool 7

None of the values are working. 

When enable logging I get this error: 

```
2023-10-08 12:10:27.225 ERROR (SyncWorker_0) [ThermiaOnlineAPI.api.ThermiaAPI] Error fetching device status. Status :404, Response: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
2023-10-08 12:10:27.609 ERROR (SyncWorker_0) [ThermiaOnlineAPI.api.ThermiaAPI] Error in getting device's register group: REG_GROUP_OPERATIONAL_STATUS, Status: 404, Response: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
2023-10-08 12:10:28.018 ERROR (SyncWorker_0) [ThermiaOnlineAPI.api.ThermiaAPI] Error in getting device's alarms. Status: 404, Response: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
2023-10-08 12:10:29.123 ERROR (SyncWorker_1) [ThermiaOnlineAPI.api.ThermiaAPI] Error fetching device status. Status :404, Response: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
2023-10-08 12:10:30.021 ERROR (SyncWorker_1) [ThermiaOnlineAPI.api.ThermiaAPI] Error in getting device's alarms. Status: 404, Response: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
2023-10-08 12:10:30.405 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform thermia
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 588, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'STATUS_HOTWATER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'STATUS_HOTWATER'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
    raise ValueError(
ValueError: Sensor sensor.heatpump_operational_status has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'STATUS_HOTWATER' (<class 'str'>)
2023-10-08 12:10:30.425 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up thermia platform for sensor
Traceback (most recent call last):
.
.
.```

**Comment by flexi80** [comment]
It a problem with Thermia not home assistant.

**Comment by AndreasBroager** [comment]
Ahh you are right. The official app for Android doesn't work either.
